# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ventamuimxN.ui'
##
## Created by: Qt User Interface Compiler version 5.15.15
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1080, 718)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(420, 650, 181, 51))
        font = QFont()
        font.setPointSize(16)
        self.pushButton_5.setFont(font)
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 650, 391, 50))
        font1 = QFont()
        font1.setPointSize(20)
        self.lineEdit_2.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(620, 570, 431, 61))
        font2 = QFont()
        font2.setPointSize(22)
        self.label_5.setFont(font2)
        self.label_5.setFrameShape(QFrame.Box)
        self.label_5.setFrameShadow(QFrame.Sunken)
        self.label_5.setLineWidth(1)
        self.tableWidget = QTableWidget(self.centralwidget)
        if (self.tableWidget.columnCount() < 5):
            self.tableWidget.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(20, 20, 581, 561))
        font3 = QFont()
        font3.setPointSize(14)
        self.tableWidget.setFont(font3)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(115)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(115)
        self.radioButton = QRadioButton(self.centralwidget)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(30, 600, 201, 31))
        self.radioButton.setFont(font3)
        self.radioButton_2 = QRadioButton(self.centralwidget)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(340, 600, 251, 31))
        self.radioButton_2.setFont(font3)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(620, 20, 431, 51))
        self.label_6.setFont(font2)
        self.label_6.setFrameShape(QFrame.Box)
        self.label_6.setFrameShadow(QFrame.Sunken)
        self.label_6.setLineWidth(1)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(620, 80, 141, 51))
        self.label_7.setFont(font2)
        self.label_7.setFrameShape(QFrame.Box)
        self.label_7.setFrameShadow(QFrame.Sunken)
        self.label_7.setLineWidth(1)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(620, 140, 431, 51))
        self.label_8.setFont(font2)
        self.label_8.setFrameShape(QFrame.Box)
        self.label_8.setFrameShadow(QFrame.Sunken)
        self.label_8.setLineWidth(1)
        self.label_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(770, 80, 281, 51))
        font4 = QFont()
        font4.setPointSize(18)
        self.comboBox.setFont(font4)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(620, 200, 431, 351))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Sunken)
        self.radioButton_3 = QRadioButton(self.frame)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(60, 30, 101, 41))
        self.radioButton_3.setFont(font3)
        self.radioButton_4 = QRadioButton(self.frame)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(260, 30, 111, 41))
        self.radioButton_4.setFont(font3)
        self.lineEdit_3 = QLineEdit(self.frame)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(190, 120, 221, 50))
        self.lineEdit_3.setFont(font1)
        self.lineEdit_4 = QLineEdit(self.frame)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(190, 200, 221, 50))
        self.lineEdit_4.setFont(font1)
        self.lineEdit_5 = QLineEdit(self.frame)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(190, 280, 221, 50))
        self.lineEdit_5.setFont(font1)
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 120, 161, 51))
        self.label_9.setFont(font2)
        self.label_9.setFrameShape(QFrame.Box)
        self.label_9.setFrameShadow(QFrame.Sunken)
        self.label_9.setLineWidth(1)
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 200, 161, 51))
        self.label_10.setFont(font2)
        self.label_10.setFrameShape(QFrame.Box)
        self.label_10.setFrameShadow(QFrame.Sunken)
        self.label_10.setLineWidth(1)
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 280, 161, 51))
        self.label_11.setFont(font2)
        self.label_11.setFrameShape(QFrame.Box)
        self.label_11.setFrameShadow(QFrame.Sunken)
        self.label_11.setLineWidth(1)
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(620, 650, 431, 51))
        self.pushButton_6.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.lineEdit_2.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"TOTAL:", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Borrar", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Producto", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Cantidad", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"P/U", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"P/C", None));
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"Busqueda por ID", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"Busqueda por nombre", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Empleado:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Cliente:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Metodo de pago:", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"Tarjeta", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"Efectivo", None))
        self.lineEdit_3.setText("")
        self.lineEdit_4.setText("")
        self.lineEdit_5.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Tarjeta", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Fecha", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"CVV", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Registrar venta", None))
    # retranslateUi

class venta(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)